
FROM rust:1.84-slim-bookworm as builder

WORKDIR /app

RUN mkdir src
RUN echo "fn main() {}" > src/main.rs
COPY Cargo.toml .

RUN cargo build --release

RUN rm src/main.rs
COPY src ./src

RUN touch src/main.rs
RUN cargo build --release

# ---------------------------------------------------
FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y imagemagick && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/release/gif-creator-api /usr/local/bin/gif-creator-api

EXPOSE 3000

CMD ["gif-creator-api"]